[package]
name = "wgpu-profiler"
version = "0.6.1"
authors = ["Andreas Reich <r_andreas2@web.de>"]
edition = "2018"
description = "Simple profiler scopes for wgpu using timer queries"
homepage = "https://github.com/Wumpf/wgpu-profiler"
repository = "https://github.com/Wumpf/wgpu-profiler"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"
resolver="2"

[lib]

[dependencies]
wgpu = "0.10"
futures-lite = "1"

[dev-dependencies]
winit = "0.25.0"
#env_logger = "0.8.2"
